/* Global state - extracted from index.original.html. */
let notes         = {};
let folders       = {};
let activeId      = null;
let activeFolderId = null;
let sidebarView   = 'notes';
let sidebarFilter = '';
let expandedFolders = new Set();
let sidebarMinimized = false; // initialised after DOM ready
let userId        = null;
let currentProfile = null;
let linkedProfiles = {};
let friends = {};
let incomingFriendRequests = {};
let sentFriendRequests = {};
let noteAccessByNote = {};
let noteAccessById = {};
let myNoteAccessByNote = {};
let profileLinkRequests = {};
let profileLinkRequestSources = {};
let readNotifications = {};
let noteAlarms = {};
let profileShareNotifications = {};
let notificationsUnavailable = false;
let saveTimer     = null;
let unsubscribe   = null;
let unsubFolders  = null;
let unsubUserDoc  = null;
let unsubProfileShares = null;
let unsubProfileLinkRequests = null;
let unsubFriends = null;
let unsubIncomingFriendRequests = null;
let unsubSentFriendRequests = null;
let unsubOwnedNoteAccess = null;
let unsubSharedWithMe = null;
let directShareUnsubs = [];
let sharedNoteUnsubs = {};   // noteId → unsubscribe fn, for real-time shared-note updates
let sharedNoteInitialLoads = {};
let sharedLibraryMeta = {};  // noteId → recipient-owned metadata, e.g. local folder placement
let removedSharedNoteIds = {}; // noteId → local removal timestamp, prevents auto re-import
let _deletePending  = null;
let _moveNoteId     = null;
let _alarmNoteId    = null;
let _alarmContext   = null;
let _alarmRefreshTimer = null;
const FOLDER_ICON_THEME = 'theme';
const FOLDER_ICON_GREY = '#8e8e93';
let _capitalizeNext = false;
let _draggingNoteId = null;
let _ctxAnchor      = null;
let _ctxCloseHandler = null;
let _mentionState   = null;
let _mentionActiveIndex = 0;
let _mentionSaveTimer = null;
let _mentionShareResolver = null;
let _pendingProfileLink = null;
let _linkedProfileRefreshTimer = null;
let _refreshingLinkedProfiles = false;
let _processingProfileLinkResponses = new Set();
let _processingAcceptedFriendRequests = new Set();
let _sendingFriendRequests = new Set();
let declinedMentionShares = new Set();

/* ── Custom Undo/Redo System ─────────────────────────── */
const undoStack = [];
const redoStack = [];
const UNDO_LIMIT = 100;
let _lastUndoSnapshot = null;
let _undoDebounceTimer = null;
let _undoTransactionOpen = false;

const _sharedNoteId   = new URLSearchParams(location.search).get('note');
const _sharedFolderId = new URLSearchParams(location.search).get('folder');
