/* Shared application state for the modular Notas app. */
let notes         = {};
let folders       = {};
let activeId      = null;
let activeFolderId = null;
let sidebarView   = 'notes';
let sidebarFilter = '';
const LAST_OPEN_NOTE_STORAGE_KEY = 'notas_last_open_note_id';
let initialNoteRestoreId = '';
let initialNoteRestorePending = false;
let noteSplitView = { peerId: '', side: 'right', awaiting: false, activePane: 'live', dividerRatio: .5 };
let expandedFolders = new Set();
let sidebarMinimized = false; // initialised after DOM ready
let userId        = null;
let currentProfile = null;
let linkedProfiles = {};
let friends = {};
let incomingFriendRequests = {};
let sentFriendRequests = {};
let noteAccessByNote = {};
let noteAccessById = {};
let myNoteAccessByNote = {};
let profileLinkRequests = {};
let profileLinkRequestSources = {};
let readNotifications = {};
let doneReminders = {};
let noteAlarms = {};
let sentReminders = {};
let profileShareNotifications = {};
let notificationsUnavailable = false;
let appNavBackStack = [];
let appNavForwardStack = [];
let appNavCurrentState = null;
let appNavCurrentKey = '';
let appNavApplying = false;
let appNavEscapeDirection = 'back';
let noteConversations = {};
let allConversations = {};
let conversationMessages = {};
let conversationMessageUnsubs = {};
let unsubNoteConversations = null;
let unsubAllConversations = null;
let activeConversationId = null;
let conversationsOpen = false;
let conversationComposeAnchor = null;
let conversationListeningNoteId = null;
let conversationBrowseView = 'all';
let conversationBrowseFolderId = null;
let conversationBrowseNoteId = null;
let conversationOverviewLoading = false;
let activeNoteBodyUnsub = null;
let activeNoteBodyListeningId = null;
let activeNoteBodyRequestSeq = 0;
let legacyBodyMigrationIds = new Set();
let saveTimer     = null;
let unsubscribe   = null;
let unsubFolders  = null;
let unsubUserDoc  = null;
let unsubProfileShares = null;
let unsubProfileLinkRequests = null;
let unsubFriends = null;
let unsubIncomingFriendRequests = null;
let unsubSentFriendRequests = null;
let unsubOwnedNoteAccess = null;
let unsubSharedWithMe = null;
let directShareUnsubs = [];
let sharedNoteUnsubs = {};   // noteId → unsubscribe fn, for real-time shared-note updates
let sharedNoteInitialLoads = {};
let sharedLibraryMeta = {};  // noteId → recipient-owned metadata, e.g. local folder placement
let removedSharedNoteIds = {}; // noteId → local removal timestamp, prevents auto re-import
let _deletePending  = null;
let _moveNoteId     = null;
let _folderModalMode = 'create';
let _folderRenameId = null;
let _alarmNoteId    = null;
let _alarmContext   = null;
let _alarmRefreshTimer = null;
const FOLDER_ICON_THEME = 'theme';
const FOLDER_ICON_GREY = '#8e8e93';
const DEFAULT_FOLDER_ICON_COLOR = FOLDER_ICON_GREY;
let _capitalizeNext = false;
let _draggingNoteId = null;
let _draggingFolderId = null;
let _ctxAnchor      = null;
let _ctxCloseHandler = null;
let _mentionState   = null;
let _mentionActiveIndex = 0;
let _mentionSaveTimer = null;
let _mentionShareResolver = null;
let _mentionSelectionPending = false;
let _conversationSelectionTimer = null;
let _conversationStarting = false;
let _conversationSending = false;
let _pendingProfileLink = null;
let _linkedProfileRefreshTimer = null;
let _refreshingLinkedProfiles = false;
let _processingProfileLinkResponses = new Set();
let _processingAcceptedFriendRequests = new Set();
let _sendingFriendRequests = new Set();
let declinedMentionShares = new Set();
const TRASH_RETENTION_DAYS = 30;

/* ── Custom Undo/Redo System ─────────────────────────── */
const undoStack = [];
const redoStack = [];
const UNDO_LIMIT = 35;
const UNDO_HTML_BUDGET = 8 * 1024 * 1024;
let _lastUndoSnapshot = null;
let _undoDebounceTimer = null;
let _undoTransactionOpen = false;
const appUndoStack = [];
const appRedoStack = [];
const APP_UNDO_LIMIT = 80;
let _appHistoryApplying = false;
let _appHistoryBusy = false;
let _lastUndoDomain = 'editor';
let _lastRedoDomain = '';
let _docTitleUndoState = null;

const _sharedNoteId   = new URLSearchParams(location.search).get('note');
const _sharedFolderId = new URLSearchParams(location.search).get('folder');

function notifyNotificationIndicatorsChanged() {
  if (typeof window.refreshDesktopNotificationBadge === 'function') {
    window.refreshDesktopNotificationBadge();
  }
  window.dispatchEvent(new CustomEvent('notas:notifications-updated'));
}
