#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

export const firebaseConfigFields = [
  {
    key: 'apiKey',
    env: 'FIREBASE_API_KEY',
    validate: value => /^AIza[0-9A-Za-z_-]{20,}$/.test(value),
    expected: 'a Firebase web API key'
  },
  {
    key: 'authDomain',
    env: 'FIREBASE_AUTH_DOMAIN',
    validate: value => /^[a-z0-9.-]+$/i.test(value) && value.includes('.') && !value.includes(':'),
    expected: 'a Firebase auth domain such as project-id.firebaseapp.com'
  },
  {
    key: 'projectId',
    env: 'FIREBASE_PROJECT_ID',
    validate: value => /^[a-z][a-z0-9-]{4,28}[a-z0-9]$/.test(value),
    expected: 'a Firebase project ID such as project-id'
  },
  {
    key: 'storageBucket',
    env: 'FIREBASE_STORAGE_BUCKET',
    validate: value => /^[a-z0-9.-]+$/i.test(value) && value.includes('.') && !value.includes(':'),
    expected: 'a Firebase Storage bucket such as project-id.firebasestorage.app'
  },
  {
    key: 'messagingSenderId',
    env: 'FIREBASE_MESSAGING_SENDER_ID',
    validate: value => /^\d+$/.test(value),
    expected: 'the numeric Firebase messaging sender ID'
  },
  {
    key: 'appId',
    env: 'FIREBASE_APP_ID',
    validate: value => /^\d+:\d+:web:[0-9a-z]+$/i.test(value),
    expected: 'a Firebase web app ID such as 1:123456789:web:abcdef'
  },
  {
    key: 'measurementId',
    env: 'FIREBASE_MEASUREMENT_ID',
    validate: value => /^G-[0-9A-Z]+$/i.test(value),
    expected: 'a Firebase measurement ID such as G-ABC123'
  }
];

export const requiredFirebaseEnvNames = firebaseConfigFields.map(field => field.env);

export function parseDotEnv(source) {
  const env = {};

  for (const rawLine of source.split(/\r?\n/)) {
    let line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    if (line.startsWith('export ')) line = line.slice('export '.length).trim();

    const separator = line.indexOf('=');
    if (separator < 1) continue;

    const key = line.slice(0, separator).trim();
    let value = line.slice(separator + 1).trim();

    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    env[key] = value;
  }

  return env;
}

export function readDotEnvFile(path) {
  return existsSync(path) ? parseDotEnv(readFileSync(path, 'utf8')) : {};
}

export function createFirebaseConfig(env) {
  return Object.fromEntries(
    firebaseConfigFields
      .map(field => [field.key, typeof env[field.env] === 'string' ? env[field.env].trim() : ''])
      .filter(([, value]) => value)
  );
}

export function isFirebasePlaceholder(value) {
  return typeof value === 'string' && /^__FIREBASE_[A-Z_]+__$/.test(value.trim());
}

export function hasFirebaseConfigValue(value) {
  return typeof value === 'string' && value.trim() && !isFirebasePlaceholder(value);
}

export function getFirebaseConfigProblems(config) {
  const missing = [];
  const malformed = [];
  const placeholders = [];

  for (const field of firebaseConfigFields) {
    const value = config[field.key];

    if (isFirebasePlaceholder(value)) {
      placeholders.push(field.env);
      missing.push(field.env);
      continue;
    }

    if (!hasFirebaseConfigValue(value)) {
      missing.push(field.env);
      continue;
    }

    if (!field.validate(value.trim())) {
      malformed.push({
        env: field.env,
        expected: field.expected
      });
    }
  }

  return { missing, malformed, placeholders };
}

export function describeFirebaseConfigProblems(problems) {
  const messages = [];

  if (problems.missing.length) {
    messages.push(`Missing Firebase config value(s): ${problems.missing.join(', ')}`);
  }

  if (problems.malformed.length) {
    messages.push(
      `Malformed Firebase config value(s): ${problems.malformed
        .map(problem => `${problem.env} should be ${problem.expected}`)
        .join('; ')}`
    );
  }

  return messages.join('. ');
}

export function assertValidFirebaseConfig(config) {
  const problems = getFirebaseConfigProblems(config);
  const description = describeFirebaseConfigProblems(problems);
  if (description) throw new Error(description);
}

export function renderFirebaseConfigScript(config, { source = 'generated' } = {}) {
  assertValidFirebaseConfig(config);

  return [
    '// Generated by scripts/firebase-config.mjs. Do not commit this file.',
    `window.NOTAS_FIREBASE_CONFIG = Object.freeze(${JSON.stringify(config, null, 2)});`,
    `window.NOTAS_FIREBASE_CONFIG_SOURCE = ${JSON.stringify(source)};`,
    ''
  ].join('\n');
}

export function renderFirebaseConfigErrorScript(message, { source = 'generated' } = {}) {
  return [
    '// Generated by scripts/firebase-config.mjs. Do not commit this file.',
    `window.NOTAS_FIREBASE_CONFIG_ERROR = ${JSON.stringify(message)};`,
    `window.NOTAS_FIREBASE_CONFIG_SOURCE = ${JSON.stringify(source)};`,
    ''
  ].join('\n');
}

function parseArgs(args) {
  const options = {
    envFile: '',
    outFile: 'firebase-config.js',
    source: process.env.GITHUB_ACTIONS === 'true' ? 'github-actions' : 'local-env'
  };

  for (const arg of args) {
    if (arg.startsWith('--env-file=')) options.envFile = arg.slice('--env-file='.length);
    else if (arg.startsWith('--out=')) options.outFile = arg.slice('--out='.length);
    else if (arg.startsWith('--source=')) options.source = arg.slice('--source='.length);
    else throw new Error(`Unknown argument: ${arg}`);
  }

  return options;
}

function main() {
  const options = parseArgs(process.argv.slice(2));
  const env = {
    ...process.env,
    ...(options.envFile ? readDotEnvFile(resolve(options.envFile)) : {})
  };
  const config = createFirebaseConfig(env);
  const script = renderFirebaseConfigScript(config, { source: options.source });
  const outFile = resolve(options.outFile);

  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, script);
  console.log(`Wrote ${outFile}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  try {
    main();
  } catch (error) {
    console.error(error.message);
    process.exit(1);
  }
}
